Repository opensearch-project/geospatial, pull requests merged in 2022-08, with the labels that each got.

#105 Add 2.2.0.0 release note
  release-notes/opensearch-geospatial.release-notes-2.2.0.0.md
Labels: v2.2.0, geospatial, release, backport 2.x

#111 Add group = 'org.opensearch' to `build.gradle`
  build.gradle
Labels: backport 2.x, backport 2.2

#116 Adding gradle task for running integ tests in remote cluster
  build.gradle
Labels: backport 2.x, backport 2.2

#119 Update opensearch build name in releases
  build.gradle
Labels: backport 2.x, backport 2.2, Infrastructure

#120 Update opensearch build name in releases
  build.gradle
Labels: v2.2.0, Infrastructure

#121 Update opensearch build name in releases to 2.x
  build.gradle
Labels: Infrastructure

#100 Add XYPoint Field Mapper
  src/main/java/org/opensearch/geospatial/index/mapper/xypoint/XYPoint.java
  src/main/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointFieldMapper.java
  src/main/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointFieldTypeParser.java
  src/main/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointParser.java
  src/main/java/org/opensearch/geospatial/plugin/GeospatialPlugin.java
  src/test/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointFieldMapperIT.java
  src/test/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointFieldMapperTests.java
  src/test/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointParsingTests.java
Labels: v2.3.0, feature, geospatial

#125 Fix typo errors
  src/test/java/org/opensearch/geospatial/index/query/xyshape/XYShapeQueryBuilderTests.java
  src/test/java/org/opensearch/geospatial/index/query/xyshape/XYShapeQueryVisitorTests.java
Labels: Refactoring, backport 2.x

#123 Add XYPoint Query Processor
  src/main/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointFieldMapper.java
  src/main/java/org/opensearch/geospatial/index/query/xypoint/XYPointQueryProcessor.java
  src/main/java/org/opensearch/geospatial/index/query/xypoint/XYPointQueryVisitor.java
  src/test/java/org/opensearch/geospatial/GeospatialRestTestCase.java
  src/test/java/org/opensearch/geospatial/index/query/AbstractXYShapeQueryTestCase.java
  src/test/java/org/opensearch/geospatial/index/query/xypoint/XYPointQueryIT.java
  src/test/java/org/opensearch/geospatial/index/query/xypoint/XYPointQueryProcessorTests.java
  src/test/java/org/opensearch/geospatial/index/query/xypoint/XYPointQueryVisitorTests.java
  src/test/java/org/opensearch/geospatial/index/query/xyshape/XYShapeQueryIT.java
Labels: feature, geospatial
