Repository opensearch-project/geospatial, pull requests merged in 2022-10, with the labels that each got.

#167 add groupId to pluginzip publication
  build.gradle
Labels: v2.4.0, backport 2.x

#134 Update to Gradle 7.5.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: backport 2.x

#173 [2.x] Add window and mac platform in CI
  .github/workflows/CI.yml
Labels: enhancement, v2.4.0

#162 Add geojson support for XYPoint
  src/main/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointParser.java
  src/test/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointFieldMapperIT.java
  src/test/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointFieldMapperTests.java
  src/test/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointParserTests.java
  src/yamlRestTest/resources/rest-api-spec/test/xypoint/10_basic.yml
Labels: enhancement

#175 [Backport 2.x] Add geojson support for XYPoint (#162)
  src/main/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointParser.java
  src/test/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointFieldMapperIT.java
  src/test/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointFieldMapperTests.java
  src/test/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointParserTests.java
  src/yamlRestTest/resources/rest-api-spec/test/xypoint/10_basic.yml
Labels: v2.4.0
