Repository opensearch-project/geospatial, pull requests merged in 2023-04, with the labels that each got.

#253 Add 2.7.0 Release Notes
  CHANGELOG.md
  release-notes/opensearch-geospatial.release-notes-2.7.0.0.md
Labels: backport 2.x, v2.7.0, skip-changelog, backport 2.7

#265 Update gradle version to 7.6
  gradle/wrapper/gradle-wrapper.properties
Labels: backport 2.x, skip-changelog

#257 Implement creation of ip2geo feature
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/RestPutDatasourceHandler.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceHelper.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceManifest.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceState.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataHelper.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoExecutorHelper.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoSettings.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/Datasource.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceExtension.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunner.java
  src/main/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoCache.java
  src/main/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessor.java
  src/main/java/org/opensearch/geospatial/plugin/GeospatialPlugin.java
  src/main/plugin-metadata/plugin-security.policy
  src/main/resources/META-INF/services/org.opensearch.jobscheduler.spi.JobSchedulerExtension
  src/main/resources/mappings/ip2geo_datasource.json
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/RestPutDatasourceHandlerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/DatasourceHelperTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataHelperTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoSettingsTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoCacheTests.java
  src/test/java/org/opensearch/geospatial/plugin/GeospatialPluginTests.java
  src/yamlRestTest/resources/rest-api-spec/test/10_basic.yml
Labels: feature, v2.8.0, skip-changelog

#268 Exclude lombok generated code from jacoco coverage report
  CHANGELOG.md
  lombok.config
Labels: backport 2.x, Infrastructure

#267 Make jacoco report to be generated faster in local
  CHANGELOG.md
  build.gradle
Labels: backport 2.x, Infrastructure
