Repository opensearch-project/geospatial, pull requests merged in 2023-05, with the labels that each got.

#275 Baseline owners and maintainers
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#271 Added unit tests with some refactoring of codes
  lombok.config
  src/main/java/org/opensearch/geospatial/annotation/VisibleForTesting.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/RestPutDatasourceHandler.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceState.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoExecutor.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoSettings.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/Datasource.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceExtension.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunner.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateService.java
  src/main/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoCache.java
  src/main/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessor.java
  src/main/java/org/opensearch/geospatial/plugin/GeospatialPlugin.java
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/RestPutDatasourceHandlerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacadeTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/DatasourceHelperTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacadeTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataHelperTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceExtensionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunnerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateServiceTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoCacheTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessorTests.java
  src/test/java/org/opensearch/geospatial/plugin/GeospatialPluginTests.java
  src/test/resources/ip2geo/manifest.json
  src/test/resources/ip2geo/manifest_invalid_url.json
  src/test/resources/ip2geo/manifest_template.json
  src/test/resources/ip2geo/sample_invalid_less_than_two_fields.csv
  src/test/resources/ip2geo/sample_valid.csv
  src/test/resources/ip2geo/sample_valid.zip
Labels: skip-changelog

#281 Add datasource name validation
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequest.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequestTests.java
Labels: skip-changelog

#282 Refactoring of code
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/Datasource.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunner.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateService.java
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/RestPutDatasourceHandlerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacadeTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunnerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateServiceTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessorTests.java
Labels: skip-changelog

#285 Change field name from md5 to sha256
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceManifest.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/Datasource.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateService.java
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacadeTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateServiceTests.java
  src/test/resources/ip2geo/manifest.json
  src/test/resources/ip2geo/manifest_invalid_url.json
  src/test/resources/ip2geo/manifest_template.json
Labels: skip-changelog

#279 Implement GET API of ip2geo datasource
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceResponse.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/RestGetDatasourceHandler.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/RestPutDatasourceHandler.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/Datasource.java
  src/main/java/org/opensearch/geospatial/plugin/GeospatialPlugin.java
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceResponseTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/RestGetDatasourceHandlerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacadeTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceExtensionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceTests.java
  src/test/java/org/opensearch/geospatial/plugin/GeospatialPluginTests.java
Labels: skip-changelog

#284 Update index option
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacade.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacadeTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacadeTests.java
Labels: skip-changelog

#289 Make some fields in manifest file as mandatory
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceManifest.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequestTests.java
Labels: skip-changelog

#283 Create datasource index explicitly
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/Datasource.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateService.java
  src/main/java/org/opensearch/geospatial/plugin/GeospatialPlugin.java
  src/main/resources/mappings/ip2geo_datasource.json
  src/main/resources/mappings/ip2geo_geoip.json
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacadeTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceExtensionTests.java
Labels: skip-changelog

#290 Add wrapper class of job scheduler lock service
  src/main/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoLockService.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoLockServiceTests.java
Labels: skip-changelog

#288 Add Auto Release Workflow
  .github/workflows/auto-release.yml
Labels: backport 2.x, skip-changelog

#293 [Refactoring]Remove all unused client attributes and more
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunner.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateService.java
  src/main/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessor.java
  src/main/java/org/opensearch/geospatial/plugin/GeospatialPlugin.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacadeTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunnerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateServiceTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessorTests.java
Labels: skip-changelog

#298 Update copyright header
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceResponse.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/RestGetDatasourceHandler.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/RestPutDatasourceHandler.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceManifest.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceState.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoExecutor.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoSettings.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/Datasource.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceExtension.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunner.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateService.java
  src/main/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessor.java
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceResponseTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/RestGetDatasourceHandlerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/RestPutDatasourceHandlerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacadeTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacadeTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoSettingsTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceExtensionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunnerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateServiceTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessorTests.java
Labels: skip-changelog

#297 Run system index handling code with stashed thread context
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacade.java
  src/main/java/org/opensearch/geospatial/shared/StashedThreadContext.java
Labels: skip-changelog

#277 Baseline owners and maintainers
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#299 Reduce lock duration and renew the lock during update
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoLockService.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/Datasource.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunner.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateService.java
  src/main/java/org/opensearch/geospatial/plugin/GeospatialPlugin.java
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacadeTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoLockServiceTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunnerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateServiceTests.java
  src/test/java/org/opensearch/geospatial/plugin/GeospatialPluginTests.java
Labels: skip-changelog

#291 Implements delete datasource API
  src/main/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/RestDeleteDatasourceHandler.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessor.java
  src/main/java/org/opensearch/geospatial/plugin/GeospatialPlugin.java
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/RestDeleteDatasourceHandlerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacadeTests.java
  src/test/java/org/opensearch/geospatial/plugin/GeospatialPluginTests.java
Labels: skip-changelog

#300 Set User-Agent in http request
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceManifest.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoSettings.java
  src/main/java/org/opensearch/geospatial/shared/Constants.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/RestPutDatasourceHandlerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/DatasourceManifestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacadeTests.java
  src/test/resources/ip2geo/manifest.json
  src/test/resources/ip2geo/manifest_invalid_url.json
  src/test/resources/ip2geo/manifest_template.json
Labels: skip-changelog

#302 Refactoring test code
  src/test/java/org/opensearch/geospatial/GeospatialRestTestCase.java
  src/test/java/org/opensearch/geospatial/processor/FeatureProcessorIT.java
Labels: skip-changelog

#303 Add ip2geo processor integ test for failure case
  src/main/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessor.java
  src/test/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessorIT.java
Labels: skip-changelog

#305 Bug fix and refactoring of code
  src/main/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoProcessorFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessor.java
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoProcessorFacadeTests.java
Labels: skip-changelog

#308 Add ConcurrentModificationException
  src/main/java/org/opensearch/geospatial/exceptions/ConcurrentModificationException.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceTransportAction.java
  src/test/java/org/opensearch/geospatial/exceptions/ConcurrentModificationExceptionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
Labels: skip-changelog

#307 Add integration test for UpdateDatasource API
  src/main/java/org/opensearch/geospatial/exceptions/IncompatibleDatasourceException.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/RestUpdateDatasourceHandler.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceTransportAction.java
  src/test/java/org/opensearch/geospatial/GeospatialRestTestCase.java
  src/test/java/org/opensearch/geospatial/exceptions/IncompatibleDatasourceExceptionTests.java
  src/test/java/org/opensearch/geospatial/exceptions/ResourceInUseExceptionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/RestUpdateDatasourceHandlerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceIT.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessorIT.java
Labels: skip-changelog

#310 Bug fix on lock management and few performance improvements
  src/main/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoLockService.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunner.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacadeTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoLockServiceTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunnerTests.java
Labels: skip-changelog

#311 Change index setting from read_only_allow_delete to write
  src/main/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacade.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacadeTests.java
Labels: skip-changelog

#314 Change package for Strings.hasText
  CHANGELOG.md
  src/main/java/org/opensearch/geospatial/action/upload/geojson/ContentBuilder.java
  src/main/java/org/opensearch/geospatial/action/upload/geojson/UploadGeoJSONRequestContent.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadMetric.java
  src/test/java/org/opensearch/geospatial/GeospatialRestTestCase.java
Labels: backport 2.x, maintenance

#313 Fix bug in get datasource API and improve memory usage
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacade.java
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacadeTests.java
Labels: skip-changelog

#319 Remove jitter and move index setting from DatasourceFacade to Datasou…
  src/main/java/org/opensearch/geospatial/ip2geo/common/DatasourceFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/Datasource.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceExtension.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceTests.java
Labels: skip-changelog

#320 Do not index blank value and do not enrich null property
  src/main/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessor.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacadeTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessorTests.java
Labels: skip-changelog

#321 Move index setting keys to constants
  src/main/java/org/opensearch/geospatial/constants/IndexSetting.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/GeoIpDataFacade.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceExtension.java
Labels: skip-changelog

#322 Return null index name for expired data
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/Datasource.java
  src/main/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessor.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceTests.java
Labels: skip-changelog

#323 Adding release notes for 2.8
  CHANGELOG.md
  release-notes/opensearch-geospatial.release-notes-2.8.0.0.md
Labels: backport 2.x, skip-changelog

#325 Add new fields in datasource
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceResponse.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/Datasource.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceTask.java
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceResponseTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceTransportActionTests.java
Labels: skip-changelog

#326 Delete index once it is expired
  src/main/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/Datasource.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunner.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateService.java
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceRunnerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateServiceTests.java
Labels: skip-changelog
