Repository opensearch-project/geospatial, pull requests merged in 2023-08, with the labels that each got.

#380 Fixed compilation errors after refactoring in core foundation classes
  CHANGELOG.md
  src/main/java/org/opensearch/geospatial/action/upload/geojson/IndexManager.java
  src/main/java/org/opensearch/geospatial/action/upload/geojson/PipelineManager.java
  src/main/java/org/opensearch/geospatial/action/upload/geojson/UploadGeoJSONResponse.java
  src/main/java/org/opensearch/geospatial/action/upload/geojson/UploadGeoJSONTransportAction.java
  src/main/java/org/opensearch/geospatial/action/upload/geojson/Uploader.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceResponse.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoLockService.java
  src/main/java/org/opensearch/geospatial/ip2geo/dao/DatasourceDao.java
  src/main/java/org/opensearch/geospatial/ip2geo/listener/Ip2GeoListener.java
  src/main/java/org/opensearch/geospatial/plugin/GeospatialPlugin.java
  src/test/java/org/opensearch/geospatial/action/upload/geojson/IndexManagerTests.java
  src/test/java/org/opensearch/geospatial/action/upload/geojson/PipelineManagerTests.java
  src/test/java/org/opensearch/geospatial/action/upload/geojson/UploaderTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoLockServiceTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/dao/DatasourceDaoTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/listener/Ip2GeoListenerTests.java
  src/test/java/org/opensearch/geospatial/plugin/GeospatialPluginTests.java
Labels: maintenance

#382 Revert datasource state when delete fails
  CHANGELOG.md
  src/main/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceTransportAction.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceTransportActionTests.java
Labels: bug, backport 2.x

#389 Update ip2geo test data url
  CHANGELOG.md
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoDataServer.java
  src/test/resources/ip2geo/server/city/manifest.json
  src/test/resources/ip2geo/server/country/manifest.json
Labels: backport 2.x

#391 Remove _primary preference from get/mget requests
  src/main/java/org/opensearch/geospatial/ip2geo/dao/DatasourceDao.java
  src/test/java/org/opensearch/geospatial/ip2geo/dao/DatasourceDaoTests.java
Labels: backport 2.x, skip-changelog, backport 2.10
