Repository opensearch-project/geospatial, pull requests merged in 2023-07, with the labels that each got.

#348 Wait until GeoIP data to be replicated to all data nodes
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateService.java
  src/test/java/org/opensearch/geospatial/ip2geo/Ip2GeoTestCase.java
  src/test/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceUpdateServiceTests.java
Labels: skip-changelog

#350 Add 2.9.0 release notes
  CHANGELOG.md
  release-notes/opensearch-geospatial.release-notes-2.9.0.0.md
Labels: backport 2.x, v2.9.0

#353 Update packages according to a change in OpenSearch core
  src/main/java/org/opensearch/geospatial/GeospatialParser.java
  src/main/java/org/opensearch/geospatial/action/upload/geojson/PipelineManager.java
  src/main/java/org/opensearch/geospatial/action/upload/geojson/UploadGeoJSONRequest.java
  src/main/java/org/opensearch/geospatial/action/upload/geojson/UploadGeoJSONResponse.java
  src/main/java/org/opensearch/geospatial/index/query/xyshape/XYShapeQueryBuilder.java
  src/main/java/org/opensearch/geospatial/plugin/GeospatialPlugin.java
  src/main/java/org/opensearch/geospatial/rest/action/upload/geojson/RestUploadGeoJSONAction.java
  src/main/java/org/opensearch/geospatial/search/aggregations/bucket/geogrid/GeoHexGrid.java
  src/main/java/org/opensearch/geospatial/search/aggregations/bucket/geogrid/GeoHexGridAggregationBuilder.java
  src/main/java/org/opensearch/geospatial/search/aggregations/bucket/geogrid/GeoHexGridBucket.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadMetric.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStats.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStatsNodeRequest.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStatsNodeResponse.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStatsRequest.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStatsResponse.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStatsTransportAction.java
  src/test/java/org/opensearch/geospatial/GeospatialParserTests.java
  src/test/java/org/opensearch/geospatial/GeospatialRestTestCase.java
  src/test/java/org/opensearch/geospatial/GeospatialTestHelper.java
  src/test/java/org/opensearch/geospatial/action/upload/geojson/UploadGeoJSONRequestTests.java
  src/test/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointParserTests.java
  src/test/java/org/opensearch/geospatial/index/query/xyshape/XYShapeQueryBuilderTests.java
  src/test/java/org/opensearch/geospatial/plugin/GeospatialPluginIT.java
  src/test/java/org/opensearch/geospatial/processor/FeatureProcessorIT.java
  src/test/java/org/opensearch/geospatial/rest/action/upload/geojson/RestUploadGeoJSONActionIT.java
  src/test/java/org/opensearch/geospatial/stats/upload/RestUploadStatsActionIT.java
  src/test/java/org/opensearch/geospatial/stats/upload/UploadMetricTests.java
  src/test/java/org/opensearch/geospatial/stats/upload/UploadStatsNodeResponseTests.java
  src/test/java/org/opensearch/geospatial/stats/upload/UploadStatsResponseTests.java
  src/test/java/org/opensearch/geospatial/stats/upload/UploadStatsTests.java
Labels: skip-changelog

#354 Update packages according to a change in OpenSearch core
  src/main/java/org/opensearch/geospatial/GeospatialParser.java
  src/main/java/org/opensearch/geospatial/action/upload/geojson/PipelineManager.java
  src/main/java/org/opensearch/geospatial/action/upload/geojson/UploadGeoJSONRequest.java
  src/main/java/org/opensearch/geospatial/action/upload/geojson/UploadGeoJSONResponse.java
  src/main/java/org/opensearch/geospatial/exceptions/ConcurrentModificationException.java
  src/main/java/org/opensearch/geospatial/exceptions/IncompatibleDatasourceException.java
  src/main/java/org/opensearch/geospatial/exceptions/ResourceInUseException.java
  src/main/java/org/opensearch/geospatial/index/query/xyshape/XYShapeQueryBuilder.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceResponse.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/dao/DatasourceDao.java
  src/main/java/org/opensearch/geospatial/ip2geo/dao/Ip2GeoCachedDao.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/Datasource.java
  src/main/java/org/opensearch/geospatial/plugin/GeospatialPlugin.java
  src/main/java/org/opensearch/geospatial/rest/action/upload/geojson/RestUploadGeoJSONAction.java
  src/main/java/org/opensearch/geospatial/search/aggregations/bucket/geogrid/GeoHexGrid.java
  src/main/java/org/opensearch/geospatial/search/aggregations/bucket/geogrid/GeoHexGridAggregationBuilder.java
  src/main/java/org/opensearch/geospatial/search/aggregations/bucket/geogrid/GeoHexGridBucket.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadMetric.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStats.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStatsNodeRequest.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStatsNodeResponse.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStatsRequest.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStatsResponse.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStatsTransportAction.java
  src/test/java/org/opensearch/geospatial/GeospatialParserTests.java
  src/test/java/org/opensearch/geospatial/GeospatialRestTestCase.java
  src/test/java/org/opensearch/geospatial/GeospatialTestHelper.java
  src/test/java/org/opensearch/geospatial/action/upload/geojson/UploadGeoJSONRequestTests.java
  src/test/java/org/opensearch/geospatial/exceptions/ConcurrentModificationExceptionTests.java
  src/test/java/org/opensearch/geospatial/exceptions/IncompatibleDatasourceExceptionTests.java
  src/test/java/org/opensearch/geospatial/exceptions/ResourceInUseExceptionTests.java
  src/test/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointParserTests.java
  src/test/java/org/opensearch/geospatial/index/query/xyshape/XYShapeQueryBuilderTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/GetDatasourceResponseTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/RestPutDatasourceHandlerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/RestUpdateDatasourceHandlerTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceIT.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/Ip2GeoLockServiceTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/dao/DatasourceDaoTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/dao/GeoIpDataDaoTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/dao/Ip2GeoCachedDaoTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/dao/Ip2GeoProcessorDaoTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessorIT.java
  src/test/java/org/opensearch/geospatial/plugin/GeospatialPluginIT.java
  src/test/java/org/opensearch/geospatial/plugin/GeospatialPluginTests.java
  src/test/java/org/opensearch/geospatial/processor/FeatureProcessorIT.java
  src/test/java/org/opensearch/geospatial/rest/action/upload/geojson/RestUploadGeoJSONActionIT.java
  src/test/java/org/opensearch/geospatial/stats/upload/RestUploadStatsActionIT.java
  src/test/java/org/opensearch/geospatial/stats/upload/UploadMetricTests.java
  src/test/java/org/opensearch/geospatial/stats/upload/UploadStatsNodeResponseTests.java
  src/test/java/org/opensearch/geospatial/stats/upload/UploadStatsResponseTests.java
  src/test/java/org/opensearch/geospatial/stats/upload/UploadStatsTests.java
Labels: skip-changelog

#361 Merge branch 'main' to feature/ip2geo
  .github/workflows/auto-release.yml
  CHANGELOG.md
  release-notes/opensearch-geospatial.release-notes-2.8.0.0.md
  release-notes/opensearch-geospatial.release-notes-2.9.0.0.md
Labels: skip-changelog

#366 Switch from XContentType to MediaType to fix compilation errors
  src/main/java/org/opensearch/geospatial/rest/action/upload/geojson/RestUploadGeoJSONAction.java
  src/test/java/org/opensearch/geospatial/OpenSearchSecureRestTestCase.java
Labels: skip-changelog

#365 Add change log for IP2Geo processor PR
  CHANGELOG.md
Labels: backport 2.x, skip-changelog

#371 Added input parameter validation with few small changes
  src/main/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceRequest.java
  src/main/java/org/opensearch/geospatial/ip2geo/common/ParameterValidator.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/Datasource.java
  src/main/java/org/opensearch/geospatial/ip2geo/jobscheduler/DatasourceExtension.java
  src/main/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessor.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/DeleteDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/PutDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceRequestTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/common/InputFormatValidatorTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/processor/Ip2GeoProcessorTests.java
Labels: backport 2.x, skip-changelog

#374 Refactor XContentFactory to MediaTypeRegistry
  src/test/java/org/opensearch/geospatial/stats/upload/TotalUploadStatsTests.java
Labels: skip-changelog

#373 Changes in invalid input handling
  src/main/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceTransportAction.java
  src/main/java/org/opensearch/geospatial/ip2geo/dao/GeoIpDataDao.java
  src/test/java/org/opensearch/geospatial/ip2geo/action/UpdateDatasourceTransportActionTests.java
  src/test/java/org/opensearch/geospatial/ip2geo/dao/GeoIpDataDaoTests.java
Labels: backport 2.x, skip-changelog
