Repository opensearch-project/geospatial, pull requests merged in 2023-03, with the labels that each got.

#237 Update snapshot version and fix compilation issues
  build.gradle
  src/test/java/org/opensearch/geospatial/action/upload/geojson/UploadGeoJSONResponseTests.java
  src/test/java/org/opensearch/geospatial/search/aggregations/bucket/geogrid/GeoHexAggregationIT.java
  src/test/java/org/opensearch/geospatial/stats/upload/UploadMetricTests.java
Labels: Infrastructure

#247 Replace Map, List, and Set in org.opensearch.common.collect with java.util references
  src/test/java/org/opensearch/geospatial/GeospatialObjectBuilder.java
  src/test/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointFieldMapperTests.java
Labels: Refactoring, backport 2.x, v2.7.0, skip-changelog

#250 [Backport 2.x] Fix upstream refactor changes
  src/main/java/org/opensearch/geospatial/action/upload/geojson/IndexManager.java
  src/main/java/org/opensearch/geospatial/action/upload/geojson/PipelineManager.java
  src/main/java/org/opensearch/geospatial/action/upload/geojson/UploadGeoJSONRequestContent.java
  src/main/java/org/opensearch/geospatial/action/upload/geojson/UploadGeoJSONResponse.java
  src/main/java/org/opensearch/geospatial/index/mapper/xypoint/XYPoint.java
  src/main/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointParser.java
  src/main/java/org/opensearch/geospatial/index/query/xyshape/XYShapeQueryBuilder.java
  src/main/java/org/opensearch/geospatial/plugin/GeospatialPlugin.java
  src/main/java/org/opensearch/geospatial/search/aggregations/bucket/geogrid/GeoHexGridAggregationBuilder.java
  src/main/java/org/opensearch/geospatial/search/aggregations/bucket/geogrid/ParsedGeoHexGrid.java
  src/main/java/org/opensearch/geospatial/search/aggregations/bucket/geogrid/ParsedGeoHexGridBucket.java
  src/main/java/org/opensearch/geospatial/stats/upload/TotalUploadStats.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadMetric.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStats.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStatsNodeResponse.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStatsResponse.java
  src/main/java/org/opensearch/geospatial/stats/upload/UploadStatsService.java
  src/test/java/org/opensearch/geospatial/GeospatialRestTestCase.java
  src/test/java/org/opensearch/geospatial/OpenSearchSecureRestTestCase.java
  src/test/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointFieldMapperTests.java
  src/test/java/org/opensearch/geospatial/index/mapper/xypoint/XYPointParserTests.java
  src/test/java/org/opensearch/geospatial/index/mapper/xyshape/XYShapeFieldMapperTests.java
  src/test/java/org/opensearch/geospatial/index/query/xyshape/XYShapeQueryBuilderTests.java
  src/test/java/org/opensearch/geospatial/index/query/xyshape/XYShapeQueryIT.java
  src/test/java/org/opensearch/geospatial/search/aggregations/bucket/geogrid/GeoHexAggregationIT.java
  src/test/java/org/opensearch/geospatial/search/aggregations/bucket/geogrid/GeoHexGridParserTests.java
  src/test/java/org/opensearch/geospatial/search/aggregations/bucket/geogrid/GeoHexGridTests.java
  src/test/java/org/opensearch/geospatial/stats/upload/TotalUploadStatsTests.java
  src/test/java/org/opensearch/geospatial/stats/upload/UploadStatsResponseTests.java
  src/test/java/org/opensearch/geospatial/stats/upload/UploadStatsServiceTests.java
  src/test/java/org/opensearch/geospatial/stats/upload/UploadStatsTests.java
Labels: Refactoring, v2.7.0, skip-changelog
