Repository opensearch-project/geospatial, pull requests merged in 2023-01, with the labels that each got.

#203 Add description to gradle to fix build error
  libs/build.gradle
Labels: backport 2.x, backport 2.5

#202 Add release notes for 2.5.0.0
  release-notes/opensearch-geospatial.release-notes-2.5.0.0.md
Labels: documentation, backport 2.x, backport 2.5

#182 Allow API to accept any index name without suffix
  src/main/java/org/opensearch/geospatial/action/upload/geojson/UploadGeoJSONRequestContent.java
  src/test/java/org/opensearch/geospatial/GeospatialRestTestCase.java
  src/test/java/org/opensearch/geospatial/GeospatialTestHelper.java
  src/test/java/org/opensearch/geospatial/action/upload/geojson/UploadGeoJSONRequestContentTests.java
  src/test/java/org/opensearch/geospatial/rest/action/upload/geojson/RestUploadGeoJSONActionIT.java
Labels: v2.6.0

#208 Upgrade snapshot version to 2.6 for 2.x
  build.gradle
Labels: maintenance
