Repository opensearch-project/geospatial, pull requests merged in 2024-03, with the labels that each got.

#635 Adjusted dependency versions to address CVEs
  CHANGELOG.md
  build.gradle
  libs/h3/build.gradle
Labels: backport 2.x, v2.13.0

#637 Add release notes for 2.13.0 release
  CHANGELOG.md
  libs/h3/LICENSE.txt
  release-notes/opensearch-geospatial.releaes-notes-2.13.0.0.md
Labels: backport 2.x

#639 Fix typo in License.TXT
  libs/h3/LICENSE.txt
Labels: backport 2.x, skip-changelog

#641 [Backport 2.x] Fix typo in License.TXT (#639)
  libs/h3/LICENSE.txt
Labels: skip-changelog

#643 Fix typo in release notes files
  release-notes/opensearch-geospatial.release-notes-2.12.0.0.md
  release-notes/opensearch-geospatial.release-notes-2.13.0.0.md
Labels: backport 2.x, skip-changelog, backport 2.13

#632 Fix flaky testGeoHexGridBucket
  src/test/java/org/opensearch/geospatial/search/aggregations/bucket/geogrid/GeoHexAggregationIT.java
Labels: backport 2.x, skip-changelog, backport 2.13
