Repository opensearch-project/geospatial, pull requests merged in 2025-04, with the labels that each got.

#737 Support phasing off SecurityManager usage in favor of Java Agent
  build.gradle
  libs/h3/build.gradle
Labels: skip-changelog

#738 Using java-agent gradle plugin to phase off Security Manager in favor of Java-agent.
  build.gradle
  libs/h3/build.gradle
Labels: skip-changelog

#742 Add missing description tag to geospatial maven pom
  build.gradle
Labels: bug, enhancement, release, skip-changelog, v3.0.0, backport 3.0

#748 Remove beta1 qualifier
  build.gradle
Labels: release, skip-changelog, v3.0.0, backport main

#750 Make sure maven publish to all versions
  .github/workflows/maven-publish.yml
Labels: release, skip-changelog, v3.0.0, backport 3.0

#746 add release notes for 3.0
  release-notes/opensearch-geospatial.release-notes-3.0.0.0.md
Labels: skip-changelog, backport 3.0
